# Generated by Django 3.2.5 on 2021-08-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
