# Generated by Django 3.2.5 on 2021-08-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputLetters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letters1', models.TextField()),
                ('letters2', models.TextField()),
                ('letters3', models.TextField()),
            ],
        ),
    ]
