# Generated by Django 3.2.6 on 2021-08-14 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='track',
        ),
        migrations.RemoveField(
            model_name='musicband',
            name='albums',
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discs.musicband'),
        ),
        migrations.AddField(
            model_name='track',
            name='music_album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discs.album'),
        ),
    ]
